<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Try not to put things in this file.
 */

// @codingStandardsIgnoreFile
/** @var $block Magento\Pwa\Block\Bundle */
?>
<!doctype html>
<html>
  <head>
    <?= /* @escapeNotVerified */ $headContent ?>
    <?= /* @escapeNotVerified */ $headAdditional ?>
  </head>
  <body>
    <div id="root"></div>
    <script src="/pub/static/frontend/Magento/venia/en_US/client.js"></script>
  </body>
</html>
